# Generated by Django 3.1.14 on 2022-01-13 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('CustumPlugins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='custumplugins_userlist', serialize=False, to='cms.cmsplugin')),
                ('first_name', models.CharField(default='Jitendra', max_length=50)),
                ('company_name', models.CharField(default='Thoughtwin', max_length=30)),
                ('contact_number', models.IntegerField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
