# Generated by Django 3.1.14 on 2022-01-14 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('CustumPlugins', '0004_admininformations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='custumplugins_contactnumber', serialize=False, to='cms.cmsplugin')),
                ('service_number', models.CharField(blank=True, default='', max_length=16, verbose_name='WhatsApp Number')),
                ('whatsapp_url', models.URLField(blank=True, default='', max_length=256, verbose_name='WhatsApp URL')),
                ('authority_number', models.CharField(blank=True, default='', max_length=16, verbose_name='Authority Number')),
            ],
            options={
                'verbose_name': 'Contact Number',
                'verbose_name_plural': 'Contact Number',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
